# Generated by Django 4.0.5 on 2022-11-14 03:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_comment_datetime_alter_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 3, 39, 15, 469934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 3, 39, 15, 469934, tzinfo=utc)),
        ),
    ]
